site:
  title: Redpanda Docs
  start_page: redpanda:introduction:intro-to-events.adoc
  url: http://localhost:8000/docs
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://github.com/JakeSCahill/redpanda-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  # Antora settings
    source-highlighter: ~
    tabs-sync-option: true
    idprefix: ''
    idseparator: '-'
    page-pagination: true
    experimental: true
  # Global variables
    latest-console-version: 2.2.2@
  # Glossary
    glossary-tooltip: 'data-tippy-content'
    terms:
    #- term: tatting
    #  definition: test
    #  link: https://www.google.com
  extensions:
  - '@asciidoctor/tabs'
  - './macros/glossary.js'
antora:
  extensions:
  - './extensions/version-fetcher/set-latest-version.js'

