site:
  title: Redpanda Docs
  start_page: ROOT:introduction:intro-to-events.adoc
  url: http://localhost:5002
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/redpanda-data/docs-site
    branches: main
    start_paths: [site-search, home, api]
ui:
  bundle:
    url: https://github.com/redpanda-data/docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - '@redpanda-data/docs-extensions-and-macros/macros/glossary'
  - '@redpanda-data/docs-extensions-and-macros/macros/config-ref'
  - '@redpanda-data/docs-extensions-and-macros/macros/helm-ref'
antora:
  extensions:
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/unlisted-pages'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/add-global-attributes'
    org: redpanda-data
    repo: docs-site
    branch: main

