site:
  title: Redpanda Docs
  start_page: 23.1@ROOT:get-started:intro-to-events.adoc
  url: http://localhost:5002
urls:
  html_extension_style: indexify
  latest_version_segment: 'current'
output:
  clean: true
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/redpanda-data/documentation
    branches: [main, v/*, '!v/23.1', api, shared, site-search]
ui:
  bundle:
    url: ../docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - '@redpanda-data/docs-extensions-and-macros/macros/glossary'
  - '@redpanda-data/docs-extensions-and-macros/macros/config-ref'
  - '@redpanda-data/docs-extensions-and-macros/macros/helm-ref'
antora:
  extensions:
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/unlisted-pages'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/add-global-attributes'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/aggregate-terms'

